"""
File: src/nse_bhavcopy/daily_signal_reporter.py
Purpose: Consolidate all daily strategy signals into a unified text advisory.
Last Modified: 2026-05-29
"""

import logging
import os
from datetime import date

import pandas as pd

LOGGER: logging.Logger = logging.getLogger(__name__)


def generate_daily_report(
    signals_dir: str = "data/signals",
    output_dir: str = "data/signals",
    date_str: str = "",
) -> str:
    """
    Consolidate all strategy signals into a unified text advisory report.

    Reads the latest CSV files generated by each scanner (RSI, DMA, Swing, Darvas),
    formats them into readable sections, writes the report to a daily text file,
    and returns the complete text content.

    Parameters:
        signals_dir (str): Directory where strategy signal CSVs are located. |
            Must exist.
        output_dir (str): Directory where the daily text report will be written. |
            Default: 'data/signals'.
        date_str (str): Date suffix for report files (YYYYMMDD). |
            Uses today's date if empty.

    Returns:
        str: Unified pre-market advisory report content.

    Complexity:
        Time: O(N) where N = total signal count across files
        Space: O(N)

    Example:
        >>> report = generate_daily_report()
        >>> "DAILY TRADING ADVISORY" in report
        True
    """
    if not date_str:
        date_str = date.today().strftime("%Y%m%d")

    os.makedirs(output_dir, exist_ok=True)

    # 1. Read files safely
    def _read_csv_safe(filename: str) -> pd.DataFrame:
        path = os.path.join(signals_dir, filename)
        if os.path.isfile(path):
            try:
                return pd.read_csv(path)
            except Exception as exc:
                LOGGER.warning("Failed to read CSV %s: %s", path, exc)
        return pd.DataFrame()

    df_rsi = _read_csv_safe(f"rsi_signals_{date_str}.csv")
    df_dma_nosl = _read_csv_safe(f"dma_bull_nosl_{date_str}.csv")
    df_dma_sl = _read_csv_safe(f"dma_bull_sl_{date_str}.csv")
    df_swing = _read_csv_safe(f"swing_target_{date_str}.csv")
    df_darvas = _read_csv_safe(f"darvas_signals_{date_str}.csv")

    lines = []
    lines.append("=" * 80)
    lines.append(
        f"     SHAREGENIUS PYTHON TRADING INTELLIGENCE SYSTEM (SPTIS) - {date_str}"
    )
    lines.append("=" * 80)
    lines.append("")

    # --- SECTION 1: RSI SCANNER (Strategy 2) ---
    lines.append("1. RSI < 35 SCANNER (Nifty 50 + Next 50 Universe)")
    lines.append("-" * 50)
    if df_rsi.empty:
        lines.append("No oversold stocks (RSI < 35) detected today.")
    else:
        # Highlight TODAY'S BUY per daily 1-stock limit rule
        top_buy = df_rsi.iloc[0]
        lines.append(
            f"--> TODAY'S PRIMARY BUY SELECTION (Lowest RSI): {top_buy['NSE Code']} "
            f"[RSI: {top_buy['RSI']:.2f}, CMP: {top_buy['CMP']:.2f}, "
            f"AMO Price: {top_buy['AMO Price']:.2f}]"
        )
        lines.append(f"    Suggested Entry Step: {top_buy['Step Hint']}")
        lines.append("")
        lines.append("    Other active RSI oversold candidate(s):")
        for _, row in df_rsi.iloc[1:].iterrows():
            lines.append(
                f"    - {row['NSE Code']}: RSI {row['RSI']:.2f} | "
                f"CMP {row['CMP']:.2f} | AMO Price {row['AMO Price']:.2f} | "
                f"{row['Step Hint']}"
            )
    lines.append("")

    # --- SECTION 2: NIFTY KI DUKAN (Strategy 1) ---
    lines.append("2. NIFTY KI DUKAN (DMA-DMA Method - Nifty 250 Universe)")
    lines.append("-" * 50)
    lines.append("Variant A: No Stop-Loss (Cheapest CMP first)")
    if df_dma_nosl.empty:
        lines.append("  No new Bull Run Variant A candidates.")
    else:
        for i, row in df_dma_nosl.head(5).iterrows():
            lines.append(
                f"  [{i+1}] {row['NSE Code']}: CMP {row['CMP']:.2f} | "
                f"%Diff 200DMA {row['%Diff 200 DMA']:.2f}% | CAR: {row['CAR']}"
            )
        if len(df_dma_nosl) > 5:
            lines.append(f"  ... and {len(df_dma_nosl) - 5} more.")

    lines.append("")
    lines.append("Variant B: With Stop-Loss / Reverse Alignment (Cheapest CMP first)")
    if df_dma_sl.empty:
        lines.append("  No new Bull Run Variant B candidates.")
    else:
        for i, row in df_dma_sl.head(5).iterrows():
            lines.append(
                f"  [{i+1}] {row['NSE Code']}: CMP {row['CMP']:.2f} | "
                f"%Diff 200DMA {row['%Diff 200 DMA']:.2f}% | CAR: {row['CAR']}"
            )
        if len(df_dma_sl) > 5:
            lines.append(f"  ... and {len(df_dma_sl) - 5} more.")
    lines.append("")

    # --- SECTION 3: SWING SCANNER (Strategy 3 & 4) ---
    lines.append("3. SWING BOTTOM-FISHING (20-Day Lows)")
    lines.append("-" * 50)
    if df_swing.empty:
        lines.append("No active swing buy candidates or GTT triggers.")
    else:
        for i, row in df_swing.head(5).iterrows():
            lines.append(
                f"  - {row['NSE Code']}: CMP {row['CMP']:.2f} | "
                f"GTT Trigger {row['GTT Trigger']:.2f} | "
                f"Target (20%): {row['GTT Target (20%)']:.2f} | "
                f"{row['Swing Signal']} ({row['Action']})"
            )
        if len(df_swing) > 5:
            lines.append(f"  ... and {len(df_swing) - 5} more.")
    lines.append("")

    # --- SECTION 4: DARVAS BOX BREAKOUTS (Strategy 7) ---
    lines.append("4. DARVAS BOX BREAKOUTS")
    lines.append("-" * 50)
    if df_darvas.empty:
        lines.append("No volume-confirmed Darvas Box breakouts or breakdowns.")
    else:
        for i, row in df_darvas.iterrows():
            lines.append(
                f"  - {row['NSE Code']}: {row['Signal']} | "
                f"CMP {row['CMP']:.2f} | Box High {row['Box High']:.2f} | "
                f"Box Low {row['Box Low']:.2f} | Consolidation: {row['Box Days']} days"
            )
    lines.append("")
    lines.append("=" * 80)
    lines.append("     END OF DAILY REPORT")
    lines.append("=" * 80)

    report_text = "\n".join(lines)

    # Save to file
    out_path = os.path.join(output_dir, f"daily_{date_str}.txt")
    try:
        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(report_text)
        LOGGER.info("Unified Daily Signal Advisory saved to %s", out_path)
    except Exception as exc:
        LOGGER.error("Failed to write daily report text file: %s", exc)

    return report_text
